# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20171017_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
