# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_auto_20190308_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
    ]
