# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_remove_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
