# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='information',
            field=models.TextField(blank=True, default=''),
        ),
    ]
