# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-11 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_auto_20190309_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
    ]
