# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-12 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_auto_20190311_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
