# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-12 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_auto_20190312_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
